//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleA.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int VisitID { get; set; }
        public int VisitNumber { get; set; }
        public System.DateTime AdmitDate { get; set; }
        public System.DateTime Discharged { get; set; }
        public int VisitDays { get; set; }
        public string Roster { get; set; }
        public string AdmitReason { get; set; }
        public string DischargeReason { get; set; }
        public string Agency { get; set; }
        public string Worker { get; set; }
        public Nullable<int> Room { get; set; }
        public Nullable<int> Bed { get; set; }
        public bool CanReturn { get; set; }
        public bool Deceased { get; set; }
        public System.DateTime EditDate { get; set; }
        public string VisitKey { get; set; }
        public byte[] v_Timestamp { get; set; }
        public int GuestID { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
